---
version: '3.3'

services:
  # docker run -d -p 8080:8080 --name erddap axiom/docker-erddap -e ERDDAP_MEMORY=64G --volumes ...
  erddap:
    container_name: erddap
    user: 0:4504  # root:imars-common
    restart: unless-stopped

    # NOTE: these values override setup.xml
    environment:
      ERDDAP_MEMORY: '64G'  # default is 4G
      ERDDAP_adminAddress: '830 1st St S, St. Petersburg, FL 33701'
      ERDDAP_adminCity: 'St. Petersburg'
      ERDDAP_adminCountry: USA
      ERDDAP_adminEmail: 'tylarmurray@usf.edu'
      ERDDAP_adminIndividualName: 'Tylar Murray'
      ERDDAP_adminInstitution: 'University of South Florida CMS IMaRS'
      ERDDAP_adminInstitutionUrl: https://imars.usf.edu
      ERDDAP_adminPhone: 555-555-5555
      ERDDAP_adminPosition: ERDDAP Administrator
      ERDDAP_adminPostalCode: 33701
      ERDDAP_adminStateOrProvince: FL
      ERDDAP_baseUrl: 'https://erddap.marine.usf.edu'
      ERDDAP_baseHttpsUrl: 'https://erddap.marine.usf.edu'
      ERDDAP_bigParentDirectory: /erddapData
      ERDDAP_emailDailyReportsTo: 'murray.tylar@gmail.com'
      ERDDAP_emailEverythingTo: 'murray.tylar@gmail.com'
      ERDDAP_emailFromAddress: 'erddap@marine.usf.edu'
      # ERDDAP_emailPassword: 
      # ERDDAP_emailProperties: 
      # ERDDAP_emailSmtpHost: 
      # ERDDAP_emailSmtpPort: 
      # ERDDAP_emailUserName: 

    image: axiom/docker-erddap:2.25.1-jdk21-openjdk
    volumes:
      - erddap-data-volume:/erddapData

      # erddap content incl. setup.xml & datasets.xml :
      - '/root/docker_volumes/erddap-config/setup.xml:/usr/local/tomcat/content/erddap/setup.xml'
      - '/root/docker_volumes/erddap-config/datasets.xml:/usr/local/tomcat/content/erddap/datasets.xml'

      # modified tomcat web.xml :
      - '/root/docker_volumes/erddap-config/web.xml:/usr/local/tomcat/conf/web.xml'

      # === ERDDAP dataset location mounts========================================
      - '/mnt/sdb:/mnt/sdb'
      - '/mnt/sdc:/mnt/sdc'
      - '/mnt/sdd:/mnt/sdd'
      - '/mnt/nvme0n1:/mnt/nvme0n1'

      # custom color palette for seascape
      - /root/docker_volumes/erddap-config/datasets/noaa_aoml_seascapes_8day/Seascapes.cpt:/usr/local/tomcat/webapps/erddap/WEB-INF/cptfiles/Seascapes.cpt
      # custom messages.xml required to have a custom color palette:
      - /root/docker_volumes/erddap-config/messages.xml:/usr/local/tomcat/webapps/erddap/WEB-INF/classes/gov/noaa/pfel/erddap/util/messages.xml

  nginx:
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./certs:/etc/nginx/certs
      
volumes:
  erddap-data-volume:
